packages:
  - 'front'
  - 'server'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false
  '@scarf/scarf': false
overrides:
  multer: 2.4.0
  proxy-addr: 2.0.8
  source-map-js: 1.2.2
  fast-uri: 3.1.8
  shell-quote: 1.12.0
  sharp: 0.35.5
